const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..');
const base=fs.readFileSync(path.join(root,'prototype/teaching-prompt.txt'),'utf8').trim();
const opening=fs.readFileSync(path.join(root,'prototype/teaching-opening.txt'),'utf8').trim();
const output='// Generated by prototype/prompt-lab/sync-prompt.cjs. Edit the canonical prompt files.\n'
 +'enum TeachingInstructions {\n    static let base = #"""\n'+base+'\n"""#\n'
 +'    static let opening = #"""\n'+opening+'\n"""#\n}\n';
const target=path.join(root,'ios/StudentHelper/TeachingInstructions.swift');
if(process.argv.includes('--check')) { if(fs.readFileSync(target,'utf8')!==output)throw Error('Web and native teaching prompts differ');console.log('PASS: web and iOS prompts match'); }
else fs.writeFileSync(target,output);
