(()=>{
 'use strict';
 const MAX_BYTES=2*1024*1024,urls=new Map();let database;
 function open(){return database??=new Promise((resolve,reject)=>{const request=indexedDB.open('yibu-images',1);request.onupgradeneeded=()=>request.result.createObjectStore('images',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>{database=null;reject(Error('图片无法保存，请检查浏览器空间'))}})}
 async function transaction(mode,work){const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('images',mode),result=work(tx.objectStore('images'));tx.oncomplete=()=>resolve(result?.result);tx.onerror=tx.onabort=()=>reject(Error('图片无法保存，请检查浏览器空间'))})}
 const read=id=>transaction('readonly',store=>store.get(id));
 async function remove(id){await transaction('readwrite',store=>store.delete(id));if(urls.has(id)){URL.revokeObjectURL(await urls.get(id));urls.delete(id)}}
 function dataURL(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('图片读取失败，请重新添加'));reader.readAsDataURL(blob)})}
 function image(url){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(Error('无法读取这张图片'));img.src=url})}
 function mime(bytes){if(bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71)return 'image/png';if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)return 'image/jpeg';const text=String.fromCharCode(...bytes.slice(0,12));if(/^GIF8[79]a/.test(text))return 'image/gif';if(text.startsWith('RIFF')&&text.slice(8)==='WEBP')return 'image/webp';return null}
 async function prepare(file){if(file.size>20*1024*1024)throw Error('图片超过 20 MB');const type=mime(new Uint8Array(await file.slice(0,12).arrayBuffer()));if(!type)throw Error('请选择 PNG、JPEG、GIF 或 WebP 图片');let blob=new Blob([file],{type});const temporary=URL.createObjectURL(blob);let img;try{img=await image(temporary)}finally{URL.revokeObjectURL(temporary)}if(img.naturalWidth*img.naturalHeight>80000000)throw Error('图片尺寸过大');let width=img.naturalWidth,height=img.naturalHeight;
  if(blob.size>MAX_BYTES||Math.max(width,height)>3200){const scale=Math.min(1,2560/Math.max(width,height)),canvas=document.createElement('canvas');canvas.width=Math.round(width*scale);canvas.height=Math.round(height*scale);const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);for(const quality of [.94,.86,.76,.65]){blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',quality));if(blob&&blob.size<=MAX_BYTES)break}width=canvas.width;height=canvas.height}
  if(!blob||blob.size>MAX_BYTES)throw Error('图片太大，请裁剪题目后重试');const id=crypto.randomUUID(),name=file.name||'作业图片.png';await transaction('readwrite',store=>store.put({id,blob}));return {id,name,type:blob.type,size:blob.size,width,height};
 }
 async function url(id){if(!urls.has(id))urls.set(id,(async()=>{const value=await read(id);if(!value?.blob)throw Error('图片未保存，请重新添加');return URL.createObjectURL(value.blob)})().catch(error=>{urls.delete(id);throw error}));return urls.get(id)}
 async function encoded(id){const value=await read(id);if(!value?.blob)throw Error('图片未保存，请重新添加');return dataURL(value.blob)}
 function references(state){return [...new Set([...state.sessions.flatMap(s=>[...(s.draftAttachments||[]),...s.messages.flatMap(m=>m.images||[])].map(i=>i.id)),...state.resources.filter(r=>r.image).map(r=>r.image.id)])]}
 async function exportAssets(state){return Promise.all(references(state).map(async id=>({id,data:await encoded(id)})))}
 async function importAssets(assets){if(!Array.isArray(assets))throw Error('图片记录格式不正确');const entries=[];for(const item of assets){if(typeof item.id!=='string'||!/^[\w-]{1,80}$/.test(item.id)||typeof item.data!=='string')throw Error('图片记录格式不正确');const match=/^data:(image\/(?:png|jpeg|gif|webp));base64,([A-Za-z0-9+/]+={0,2})$/.exec(item.data);if(!match||match[2].length>Math.ceil(MAX_BYTES*4/3)+4)throw Error('图片记录格式不正确');const bytes=Uint8Array.from(atob(match[2]),c=>c.charCodeAt(0));if(mime(bytes)!==match[1])throw Error('图片记录格式不正确');entries.push({id:item.id,blob:new Blob([bytes],{type:match[1]})})}await transaction('readwrite',store=>entries.forEach(item=>store.put(item)));for(const value of urls.values())URL.revokeObjectURL(await value.catch(()=>''));urls.clear()}
 function hydrate(root=document){root.querySelectorAll('img[data-image-id]:not([data-loading])').forEach(img=>{img.dataset.loading='true';url(img.dataset.imageId).then(value=>{if(img.isConnected){img.src=value;img.classList.add('ready')}}).catch(()=>{if(img.isConnected){img.alt='图片未保存，请重新添加';img.closest('button')?.classList.add('yb-image-missing')}})})}
 window.StudentImages={prepare,read,remove,url,encoded,references,exportAssets,importAssets,hydrate};
})();
