/* Product state and services. Visuals live in workspace.js / workspace.css. */
(()=>{
 const key='yibu-prototype-v1';
 const question='设 0 < P(A) < 1，0 < P(B) < 1，且 P(A | B) + P(A̅ | B̅) = 1，证明 A 与 B 独立。';
 const seed={courses:[],course:'',sessions:[{id:1,title:'新对话',course:'',stage:0,messages:[],draft:'',done:false}],current:1,resources:[]};
 let state;try{state=JSON.parse(localStorage.getItem(key))||structuredClone(seed)}catch{state=structuredClone(seed)}
 if(!Array.isArray(state.courses)||!Array.isArray(state.sessions)||!Array.isArray(state.resources))state=structuredClone(seed);
 state.sessions.forEach(s=>{s.messages=Array.isArray(s.messages)?s.messages:[]});
 if(!state.sessions.length)state.sessions=structuredClone(seed.sessions);
 if(!state.sessions.some(s=>s.id===state.current))state.current=state.sessions[0].id;
 const pending=new Set(),imageBusy=new Set();const requests=new Map(),imageJobs=new Map();
 const notify=(type='state')=>window.dispatchEvent(new CustomEvent('student:change',{detail:type}));
 const persist=(type)=>{try{localStorage.setItem(key,JSON.stringify(state))}catch{notify('storage-error')}if(type)notify(type)};
 const current=()=>state.sessions.find(s=>s.id===state.current);
 function parseQuestions(text){const pattern=/^\s*(?:第\s*(\d+)\s*题\s*[：:、.．]?|(\d{1,3})[.．、)）])\s*/gm;const matches=[...text.matchAll(pattern)];if(matches.length<2)return [];const questions=matches.map((m,i)=>({number:Number(m[1]||m[2]),text:text.slice(m.index+m[0].length,matches[i+1]?.index??text.length).trim()}));return questions.every(q=>q.text.length>=8&&/求|证明|计算|设|若|已知|试|判断|解|积分|极限/.test(q.text))?questions:[]}
 function canNext(){const s=current();return Array.isArray(s.questionQueue)&&s.questionQueue.length>1&&(s.questionIndex||0)<s.questionQueue.length-1}
 function create(course=state.course){const s={id:Date.now(),title:'新对话',course,stage:0,messages:[],done:false,draft:''};while(state.sessions.some(x=>x.id===s.id))s.id++;state.sessions.unshift(s);state.current=s.id;state.course=course;persist('navigate');return s}
 function select(id){const item=state.sessions.find(s=>s.id===id);if(!item)return;state.current=id;state.course=item.course||'';persist('navigate')}
 function addCourse(name){name=name.trim();if(!name)return false;if(!state.courses.includes(name))state.courses.push(name);state.course=name;persist('courses');return true}
 function renameSession(id,name){const s=state.sessions.find(s=>s.id===id);name=name.trim().slice(0,80);if(!s||!name)return false;s.title=name;s.titleEdited=true;persist('session-title');return true}
 function deleteCourse(name){if(!state.courses.includes(name))return;const removed=state.sessions.filter(s=>s.course===name),before=new Set(StudentImages.references(state));for(const s of removed){requests.get(s.id)?.abort();pending.delete(s.id)}state.courses=state.courses.filter(c=>c!==name);state.sessions=state.sessions.filter(s=>s.course!==name);state.resources=state.resources.filter(f=>f.course!==name);if(state.courseColors)delete state.courseColors[name];const kept=new Set(StudentImages.references(state));for(const id of before)if(!kept.has(id))StudentImages.remove(id).catch(()=>{});const course=state.course===name?(state.courses[0]||''):state.course;if(!state.sessions.some(s=>s.id===state.current)){const replacement=state.sessions.find(s=>s.course===course)||state.sessions[0];if(replacement){state.current=replacement.id;state.course=replacement.course||''}else{create(course);return}}else state.course=course;persist('navigate')}
 function plain(html){const element=document.createElement('template');element.innerHTML=html||'';element.content.querySelectorAll('script,style,iframe,object').forEach(n=>n.remove());element.content.querySelectorAll('br').forEach(br=>br.replaceWith('\n'));return element.content.textContent||''}
 async function reply(s){
  if(pending.has(s.id))return;
  pending.add(s.id);s.failure=null;notify('messages');
  const controller=new AbortController();requests.set(s.id,controller);const timeout=setTimeout(()=>controller.abort(),95000);
  try{
   const all=s.messages.filter(m=>['user','teacher','paper'].includes(m.role));const recent=all.slice(-80);const paper=all.findLast(m=>m.role==='paper');if(paper&&!recent.includes(paper))recent.unshift(paper);
   const included=new Set(recent.flatMap(m=>m.images||[]).slice(-8).map(i=>i.id));
   const messages=await Promise.all(recent.map(async m=>{const text=m.text||plain(m.html),images=(m.images||[]).filter(i=>included.has(i.id));let content=text;if(images.length)content=[{type:'text',text:text||'请从图中的题目开始，一次只教一步。'},...await Promise.all(images.map(async i=>({type:'image_url',image_url:{url:await StudentImages.encoded(i.id)}})))];else if(m.images?.length)content=(text?text+'\n':'')+'较早的作业图片已超出本次图片上下文，若需要查看该图，请让学生重新发送。';return {role:m.role==='teacher'?'assistant':'user',content}}));
   const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages}),signal:controller.signal});
   const data=await response.json();if(!response.ok)throw Error(data.error||'暂时无法回复，请重试');if(typeof data.reply!=='string'||!data.reply.trim())throw Error('没有收到回复，请重试');
   s.messages.push({role:'teacher',text:data.reply});s.failure=null;
  }catch(error){s.failure=error.name==='AbortError'?'回复超时，请重试':error.message||'连接失败，请重试'}
  finally{clearTimeout(timeout);requests.delete(s.id);pending.delete(s.id);persist('messages')}
 }
 async function send(text){text=text.trim();const s=current(),images=s.draftAttachments||[];if((!text&&!images.length)||pending.has(s.id)||imageBusy.has(s.id))return;s.draft='';s.draftAttachments=[];if(!s.messages.length&&!s.titleEdited&&['新对话','新会话'].includes(s.title))s.title=text.slice(0,22)||'图片作业';const questions=parseQuestions(text);if(questions.length){s.questionQueue=questions;s.questionIndex=0}s.messages.push({role:questions.length&&!images.length?'paper':'user',text,...(images.length?{images}:{} )});s.waitingQuestion=false;s.live=true;persist('messages');notify('attachments');await reply(s)}
 function draft(text){current().draft=text;persist()}
 async function resources(files,course=state.course){for(const file of files){if(course&&!state.courses.includes(course))return;const image=/^image\//.test(file.type)||/\.(png|jpe?g|gif|webp)$/i.test(file.name)?await StudentImages.prepare(file):null;if(course&&!state.courses.includes(course)){if(image)await StudentImages.remove(image.id);return}state.resources.push({name:file.name,course,...(image?{image}:{})});persist('resources')}}
 function removeResource(index){const file=state.resources.splice(index,1)[0];persist('resources');if(file?.image&&!StudentImages.references(state).includes(file.image.id))StudentImages.remove(file.image.id).catch(()=>{})}
 function useResource(index){const file=state.resources[index];if(!file?.image)return;let s=current();if(s.course!==file.course){s=state.sessions.find(s=>s.course===file.course)||create(file.course);select(s.id)}if((s.draftAttachments||[]).length>=4)throw Error('一次最多添加 4 张图片');if(!s.draftAttachments?.some(i=>i.id===file.image.id))(s.draftAttachments??=[]).push({...file.image,name:file.name});persist('attachments')}
 function attach(files){current().messages.push({role:'user',text:'附件：'+files.map(file=>file.name).join('、')});persist('messages')}
 async function attachImages(files,id=state.current){const previous=imageJobs.get(id)||Promise.resolve();imageBusy.add(id);notify('attachments');const task=previous.catch(()=>{}).then(async()=>{for(const file of files){const s=state.sessions.find(s=>s.id===id);if(!s)return;if((s.draftAttachments||[]).length>=4)throw Error('一次最多添加 4 张图片');const image=await StudentImages.prepare(file);if(!state.sessions.includes(s)){await StudentImages.remove(image.id);return}(s.draftAttachments??=[]).push(image);persist('attachments')}});imageJobs.set(id,task);try{await task}finally{if(imageJobs.get(id)===task){imageJobs.delete(id);imageBusy.delete(id);notify('attachments')}}}
 function removeImage(id){const s=current();s.draftAttachments=(s.draftAttachments||[]).filter(i=>i.id!==id);persist('attachments');if(!StudentImages.references(state).includes(id))StudentImages.remove(id).catch(()=>{})}
 async function exportState(){if(imageBusy.size)throw Error('请等待图片读取完成');const value=structuredClone(state);value.imageAssets=await StudentImages.exportAssets(value);return value}
 function record(){return state.sessions.find(s=>s.course===state.course&&s.messages.some(m=>m.role==='paper'&&m.text===question))}
 async function nextQuestion(){const s=current();if(pending.has(s.id)||!canNext())return;s.questionIndex=(s.questionIndex||0)+1;const question=s.questionQueue[s.questionIndex];s.messages.push({role:'divider',text:'第 '+question.number+' 题'},{role:'paper',text:question.text});s.waitingQuestion=false;persist('messages');await reply(s)}
 function deleteSession(id){const s=state.sessions.find(s=>s.id===id);if(!s)return;requests.get(id)?.abort();pending.delete(id);state.sessions=state.sessions.filter(s=>s.id!==id);const kept=new Set(StudentImages.references(state));for(const image of [...(s.draftAttachments||[]),...s.messages.flatMap(m=>m.images||[])])if(!kept.has(image.id))StudentImages.remove(image.id).catch(()=>{});if(id===state.current){const replacement=state.sessions.find(x=>x.course===s.course)||state.sessions[0];if(replacement){state.current=replacement.id;state.course=replacement.course||''}else{create(s.course);return}}persist('navigate')}
 function review(s,status){s.reviewStatus=status;persist('review')}
 async function importState(value){if(!value||!Array.isArray(value.courses)||!value.courses.every(c=>typeof c==='string')||!Array.isArray(value.sessions)||!value.sessions.length||!Array.isArray(value.resources)||!value.sessions.every(s=>typeof s.title==='string'&&typeof s.course==='string'&&Array.isArray(s.messages)&&s.messages.every(m=>typeof m.role==='string'&&(typeof m.text==='string'||typeof m.html==='string')))||!value.resources.every(r=>typeof r.name==='string'&&typeof r.course==='string'))throw Error('文件格式不正确');for(const s of value.sessions)for(const list of [s.draftAttachments,...s.messages.map(m=>m.images)])if(list!==undefined&&(!Array.isArray(list)||!list.every(i=>typeof i.id==='string'&&/^[\w-]{1,80}$/.test(i.id)&&typeof i.name==='string')))throw Error('图片记录格式不正确');await StudentImages.importAssets(value.imageAssets||[]);state.courses=value.courses;state.sessions=value.sessions;state.resources=value.resources;state.course=value.course||'';state.current=value.sessions.some(s=>s.id===value.current)?value.current:value.sessions[0].id;state.courseColors=value.courseColors||{};persist('import')}
 persist();
 window.StudentStore={state,current,create,select,addCourse,deleteCourse,renameSession,send,retry:()=>reply(current()),draft,resources,removeResource,useResource,attach,attachImages,removeImage,imageBusy,exportState,record,question,plain,pending,persist,nextQuestion,canNext,parseQuestions,deleteSession,review,importState};
})();
