const assert = require('node:assert/strict');
const fs = require('node:fs');
let playwright; try { playwright = require('playwright'); } catch { playwright = require('C:/Users/kkk/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'); }
async function run() {
  fs.mkdirSync('prototype/screenshots',{recursive:true});
  const browser = await playwright.chromium.launch({headless:true,channel:'msedge'});
  try {
    const context = await browser.newContext({viewport:{width:1440,height:900}});
    const page = await context.newPage(), errors = [];
    page.on('pageerror',error=>errors.push(error.message));
    let requestCount = 0;
    await page.route('**/api/chat',async route=>{
      requestCount++;
      await new Promise(resolve=>setTimeout(resolve,300));
      await route.fulfill({status:requestCount===2?502:200,contentType:'application/json',body:JSON.stringify(requestCount===2?{error:'连接失败，请重试'}:{reply:'先看这一小步：两个条件概率相等。你能写出这个等式吗？'})});
    });
    await page.goto('http://127.0.0.1:4174');
    await page.waitForTimeout(350);
    assert.equal(await page.locator('[data-action="sample"]').count(),0);
    assert.equal(await page.locator('.yb-teacher').count(),0);
    assert.deepEqual(await page.evaluate(()=>StudentStore.state.courses),[]);
    await page.evaluate(()=>{StudentStore.addCourse('数学');StudentStore.current().course='数学';StudentStore.current().messages=[{role:'user',text:'先做第 24 题。'},{role:'paper',text:StudentStore.question},{role:'teacher',text:'先看目标：P(A | B) = P(A)'}];StudentStore.persist()});
    await page.reload();
    assert.equal(await page.locator('.yb-session.selected').count(),1,'current course expands');
    assert.equal(await page.locator('.yb-teacher').count(),1);
    assert.equal(await page.locator('[data-action="next"]').count(),0,'single question has no next action');
    await page.locator('#answer-input').fill('这两个相等，所以就独立吗？');
    await page.locator('.yb-send').click();
    await page.locator('#new-chat').click();
    const secondID = await page.evaluate(()=>StudentStore.state.current);
    await page.locator('#answer-input').fill('这个会话的草稿');
    await page.locator('[data-action="session"][data-session="1"]').click();
    await page.waitForTimeout(400);
    assert.equal(await page.evaluate(()=>StudentStore.state.sessions.find(s=>s.id===1).messages.at(-1).role),'teacher');
    assert.equal(await page.evaluate(id=>StudentStore.state.sessions.find(s=>s.id===id).draft,secondID),'这个会话的草稿');
    await page.locator('[data-action="tab"][data-view="records"]').click();
    await page.locator('#record-search').fill('不存在的题目');
    assert.equal(await page.locator('.yb-record-row').count(),0);
    await page.locator('#record-search').fill('独立性');
    await page.locator('[data-action="detail"]').click();
    assert.equal(await page.locator('details').first().getAttribute('open'),null);
    assert.match(await page.locator('.yb-quote').innerText(),/这两个相等/);
    await page.locator('details').first().locator('summary').click();
    await page.waitForTimeout(300);
    assert.equal(await page.locator('details').first().getAttribute('open'),'');
    await page.locator('details').last().locator('summary').click();
    await page.waitForTimeout(300);
    assert.ok(await page.locator('.yb-history .yb-msg').count()>=5);
    await page.screenshot({path:'prototype/screenshots/opus-record.png',fullPage:true});
    await page.locator('[data-action="continue-record"]').click();
    await page.locator('#answer-input').fill('这个请求测试失败重试');
    await page.locator('.yb-send').click();
    await page.waitForSelector('.yb-fail');
    await page.locator('[data-action="retry"]').click();
    await page.waitForTimeout(400);
    assert.equal(await page.locator('.yb-fail').count(),0);
    await page.locator('#new-chat').click();
    await page.locator('#answer-input').fill('24. 设 P(A|B)+P(非A|非B)=1，证明 A 与 B 独立。\n25. 若 A、B 独立且概率均为正，证明 A、B 相容。');
    await page.locator('.yb-send').click();
    await page.waitForTimeout(400);
    assert.equal(await page.locator('[data-action="next"]').count(),1,'provided batch enables next');
    await page.locator('[data-action="next"]').click();
    await page.waitForTimeout(400);
    assert.equal(await page.locator('[data-action="next"]').count(),0,'last provided question has no next');
    assert.match(await page.evaluate(()=>StudentStore.current().messages.at(-2).text),/相容/);
    assert.equal(await page.evaluate(()=>StudentStore.current().messages.at(-2).role),'paper');
    await page.locator('[data-action="jump"]').click();
    await page.locator('[data-action="jump-to"]').first().click();
    await page.locator('[data-action="tab"][data-view="files"]').click();
    await page.locator('#file-input').setInputFiles({name:'课堂资料.txt',mimeType:'text/plain',buffer:Buffer.from('read-only test filename')});
    // Input context is deliberately selected through the visible add action below.
    await page.locator('[data-action="add-files"]').click();
    await page.locator('#file-input').setInputFiles({name:'老师课件.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-test')});
    assert.match(await page.locator('.yb-file').innerText(),/老师课件/);
    await page.locator('[data-action="add-course"]').click();
    assert.equal(await page.locator('#create-course').isDisabled(),true);
    await page.locator('#course-name').fill('大学物理');
    await page.locator('#create-course').click();
    await page.waitForSelector('.yb-welcome');
    assert.match(await page.locator('#navigation').innerText(),/大学物理/);
    await page.locator('#answer-input').fill('物理草稿');
    await page.reload();
    assert.equal(await page.locator('#answer-input').inputValue(),'物理草稿');
    await page.locator('[data-action="course"][data-course=""]').click();
    assert.equal(await page.locator('#tabs button').count(),0);
    assert.equal(await page.locator('[data-action="attach"]').count(),1);
    const deletedID = await page.evaluate(()=>StudentStore.state.current);
    await page.locator('[data-action="session-menu"][data-session="'+deletedID+'"]').click();
    await page.locator('[data-action="delete-session"]').click();
    await page.locator('#confirm-delete').click();
    await page.waitForTimeout(220);
    assert.equal(await page.evaluate(id=>StudentStore.state.sessions.some(s=>s.id===id),deletedID),false);
    await page.locator('#account').click();
    const downloadPromise = page.waitForEvent('download');
    await page.locator('[data-action="export"]').click();
    const download = await downloadPromise;
    const exported = JSON.parse(fs.readFileSync(await download.path(),'utf8'));
    assert.ok(exported.courses.includes('大学物理'));
    assert.equal(errors.length,0,errors.join('\n'));
    await context.close();
    const mobile = await browser.newContext({viewport:{width:402,height:874},isMobile:true,hasTouch:true,reducedMotion:'reduce'});
    const phone = await mobile.newPage();
    phone.on('pageerror',error=>errors.push(error.message));
    await phone.goto('http://127.0.0.1:4174');
    await phone.waitForTimeout(200);
    assert.equal(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    await phone.locator('#mobile-menu').click();
    await phone.waitForTimeout(150);
    assert.equal(await phone.locator('#sidebar').evaluate(e=>e.classList.contains('open')),true);
    await phone.locator('[data-action="add-course"]').click();
    await phone.locator('#course-name').fill('手机课程');
    await phone.locator('#create-course').click();
    await phone.waitForTimeout(200);
    assert.equal(await phone.locator('#sidebar').evaluate(e=>e.classList.contains('open')),false);
    await phone.evaluate(()=>{StudentStore.addCourse('数学');StudentStore.create('数学');StudentStore.current().messages=[{role:'paper',text:StudentStore.question},{role:'teacher',text:'先看目标：P(A | B) = P(A)'}];StudentStore.persist('messages')});
    await phone.waitForTimeout(200);
    await phone.screenshot({path:'prototype/screenshots/opus-mobile.png',fullPage:true});
    assert.equal(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    assert.equal(await phone.locator('.yb-send').evaluate(e=>e.getBoundingClientRect().height>=44),true);
    assert.equal(errors.length,0,errors.join('\n'));
    await mobile.close();
    console.log('PASS: desktop + 402x874 mobile; isolated requests, drafts, retries, records, search, files, export, navigation, reduced motion.');
  } finally { await browser.close(); }
}
run().catch(error=>{console.error(error);process.exitCode=1});
