(()=>{
 'use strict';
 const S=window.StudentStore,$=q=>document.querySelector(q),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const paths={pen:'<path d="M12 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7M16 3l5 5M10 14l1-5 8-8 5 5-8 8-6 1Z"/>',chat:'<path d="M21 11.5a8.5 8.5 0 0 1-8.5 8.5H4l-2 2V11.5a9.5 9.5 0 0 1 19 0Z"/>',book:'<path d="M5 3h14a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2ZM7 3v18M11 8h5M11 12h5M11 16h3"/>',clip:'<path d="m8 13 7-7a3 3 0 0 1 4 4l-9 9a5 5 0 0 1-7-7L13 2a4 4 0 0 1 6 6L9 18"/>',chevron:'<path d="m9 5 7 7-7 7"/>',plus:'<path d="M12 5v14M5 12h14"/>',up:'<path d="m6 12 6-6 6 6M12 6v13"/>',down:'<path d="m6 12 6 6 6-6M12 5v13"/>',back:'<path d="m12 5-7 7 7 7M5 12h15"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',disk:'<rect x="3" y="4" width="18" height="16" rx="3"/><path d="M3 14h18M7 17h.01M11 17h.01"/>',cloud:'<path d="m3 3 18 18M6 6a6 6 0 0 1 11 1 5 5 0 0 1 3 9M6 10a5 5 0 0 0-1 10h12"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',filter:'<path d="M4 6h16M7 12h10M10 18h4"/>',repeat:'<path d="m17 2 4 4-4 4M21 6H7a4 4 0 0 0-4 4M7 22l-4-4 4-4M3 18h14a4 4 0 0 0 4-4"/>',eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7-10-7-10-7Z"/><circle cx="12" cy="12" r="3"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 0 1 6 0c0 2-3 2-3 4M12 17h.01"/>',retry:'<path d="M3 11a9 9 0 1 1 3 8M3 3v8h8"/>',file:'<path d="M14 2H5a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V9ZM14 2v7h7M7 14h10M7 18h6"/>',check:'<path d="m5 12 4 4L19 6"/>',more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',upload:'<path d="M12 16V4m-5 5 5-5 5 5M4 16v5h16v-5"/>'};
 const icon=(name,cl='')=>`<svg class="${cl}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.book}</svg>`;
 const colors=['#2A57C4','#1F8A70','#C0572B','#7A4FC0','#B0892A','#C23F6E'];
 const answer='由 P(A̅ | B̅) = 1 − P(A | B̅)，代入条件得 P(A | B) = P(A | B̅) = q。\n由全概率公式，P(A) = qP(B) + qP(B̅) = q。\n因此 P(A | B) = P(A)，A 与 B 独立。';
 let view='chat',query='',askedOnly=false,expanded=S.state.course||'',renderedSession=null,menuAnchor=null,navFocus=null,uploadContext='chat',newReply=false,toastTimer,draftTimer,dialogClosing=false;
 const positions=new Map(),motion=new WeakMap();let pageVersion=0;
 const reduce=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
 function animate(el,frames,ms=200,exit=false,delay=0){if(!el)return Promise.resolve();motion.get(el)?.cancel();if(reduce()){frames=frames.map(f=>({opacity:f.opacity??1}));ms=120;delay=0}const a=el.animate(frames,{duration:ms,easing:reduce()?'linear':exit?'cubic-bezier(.4,0,1,1)':'cubic-bezier(.2,0,0,1)',delay,fill:'none'});motion.set(el,a);return a.finished.catch(()=>{})}
 function illustration(type){const art=type==='paper'?'<rect x="27" y="13" width="65" height="72" rx="5"/><path d="M39 33h40M39 45h34M39 57h40M77 19l16 16M55 73l5-13 37-37 8 8-37 37-13 5Z"/><path d="m55 73 5-13" stroke="var(--accent)"/>':type==='file'?'<rect x="30" y="17" width="62" height="68" rx="5"/><path d="m48 25 13-13a10 10 0 0 1 14 14L52 49a7 7 0 0 1-10-10l23-23" stroke="var(--accent)"/>':'<rect x="28" y="16" width="65" height="68" rx="6"/><path d="M39 16v68M49 38h30M49 49h22"/><path d="M73 16v24l7-5 7 5V16" stroke="var(--accent)"/>';return `<svg class="yb-illustration" viewBox="0 0 120 96" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round" aria-hidden="true">${art}</svg>`}
 function btn(action,label,ico,kind='yb-ghost',extra=''){return `<button class="yb-btn ${kind}" data-action="${action}" ${extra}>${ico?icon(ico):''}${esc(label)}</button>`}
 function flushDraft(){clearTimeout(draftTimer);S.persist()}
 function route(v='chat'){flushDraft();closePopover();closeNav();const hash=v==='chat'?`#/chat/${S.state.current}`:`#/c/${encodeURIComponent(S.state.course)}/${v}`;if(location.hash===hash)render(v);else location.hash=hash}
 function parseRoute(){const parts=location.hash.slice(2).split('/');let v='chat';if(parts[0]==='chat'){const s=S.state.sessions.find(s=>String(s.id)===parts[1]);if(s){S.state.current=s.id;S.state.course=s.course||''}}else if(parts[0]==='c'){try{const c=decodeURIComponent(parts[1]);if(S.state.courses.includes(c)){S.state.course=c;v=parts.slice(2).join('/')||'chat'}}catch{}}expanded=S.state.course;S.persist();render(['records','records/24','review','files'].includes(v)?v:'chat')}
 function renderSidebar(){const previous=[...$('#navigation').querySelectorAll('.yb-course.expanded')].map(e=>e.dataset.group);const group=(course,i)=>{const list=S.state.sessions.filter(s=>(s.course||'')===course),open=expanded===course,color=S.state.courseColors?.[course]||colors[i%6];return `<div class="yb-course ${open?'expanded':''} ${S.state.course===course?'selected':''}" data-group="${esc(course)}"><button class="yb-navrow" data-action="course" data-course="${esc(course)}" aria-expanded="${open}">${course?icon('chevron','yb-chevron')+`<i class="yb-course-dot" style="background:${colors.includes(color)?color:colors[0]}"></i>`:icon('chat')}<span class="yb-nav-name">${esc(course||'普通对话')}</span>${list.length?`<span class="yb-count">${list.length}</span>`:''}</button><div class="yb-session-group"><div class="yb-session-inner">${list.slice(0,8).map(s=>`<div class="yb-session-wrap"><button class="yb-navrow yb-session ${s.id===S.state.current&&view==='chat'?'selected':''}" data-action="session" data-session="${s.id}" ${s.id===S.state.current&&view==='chat'?'aria-current="page"':''}>${s.draft?'<span class="yb-draft">草稿·</span>':''}<span class="yb-nav-name">${esc(s.title)}</span>${S.pending.has(s.id)?'<i class="yb-save-dot" aria-label="正在回复"></i>':s.messages.some(m=>m.record)?icon('book'):''}</button>${btn('session-menu','','more','yb-icon yb-session-more',`aria-label="管理 ${esc(s.title)}" data-session="${s.id}"`)}</div>`).join('')}${list.length>8?`<button class="yb-navrow yb-all" data-action="sessions" data-course="${esc(course)}">全部 ${list.length} 条 ${icon('chevron')}</button>`:''}</div></div></div>`};$('#navigation').innerHTML=group('',0)+`<div class="yb-group-title">课程${btn('add-course','','plus','yb-icon','aria-label="新建课程" title="新建课程"')}</div>`+S.state.courses.map(group).join('');$('#navigation').querySelectorAll('.yb-course').forEach(el=>{const isOpen=el.classList.contains('expanded');if(previous.includes(el.dataset.group)!==isOpen){el.classList.toggle('expanded',!isOpen);requestAnimationFrame(()=>el.classList.toggle('expanded',isOpen))}})}
 function renderHeader(){const course=S.state.course;$('#top-title').textContent=view==='chat'?S.current().title:course;const active=view.startsWith('records')||view==='review'?'records':view==='files'?'files':'chat';if(course){if(!$('#tabs').children.length)$('#tabs').innerHTML=[['chat','对话','chat'],['records','记录','book'],['files','资料','clip']].map(([v,t,i])=>`<button class="yb-tab" data-action="tab" data-view="${v}">${icon(i)}${t}</button>`).join('')+'<i class="yb-tab-line"></i>';$('#tabs').querySelectorAll('.yb-tab').forEach(b=>{b.classList.toggle('active',b.dataset.view===active);b.setAttribute('aria-current',b.dataset.view===active?'page':'false')});requestAnimationFrame(tabIndicator)}else $('#tabs').innerHTML='';const questions=S.current().messages.map((m,i)=>({m,i})).filter(x=>['paper','divider'].includes(x.m.role));$('#question-jump').innerHTML=view==='chat'&&questions.length>=2?btn('jump','题目','chevron','yb-ghost','aria-label="跳转题目"'):''}
 function tabIndicator(){const active=$('#tabs .active'),line=$('#tabs .yb-tab-line');if(!active||!line)return;line.style.width=active.offsetWidth+'px';line.style.transform=`translateX(${active.offsetLeft}px)`}
 function render(v=view,immediate=false){if(!immediate&&view!==v&&$('#stage').firstElementChild){const version=++pageVersion;animate($('#stage').firstElementChild,[{opacity:1},{opacity:0}],120,true).then(()=>{if(version===pageVersion)render(v,true)});return}pageVersion++;const scroll=$('.yb-chat-scroll');if(scroll&&renderedSession!==null)positions.set(renderedSession,scroll.scrollTop);const changed=view!==v;view=v;renderedSession=null;renderSidebar();renderHeader();if(v==='chat')renderChat();else{const detail=v==='records/24';$('#stage').innerHTML=`<div class="yb-page-scroll"><div class="yb-page ${detail?'yb-detail':''}">${v==='files'?filesPage():v==='review'?reviewPage():detail?detailPage():recordsPage()}</div></div>`;if(v==='records')renderResults();if(changed)animate($('.yb-page'),[{opacity:0,transform:'translateX(12px)'},{opacity:1,transform:'translateX(0)'}],200);if(v==='review'&&S.record()?.reviewStatus==='know')reviewComplete()} }
 function rich(m){if(m.text!==undefined)return esc(m.text);const template=document.createElement('template');template.innerHTML=m.html||'';function node(n){if(n.nodeType===3)return esc(n.textContent);if(n.nodeType!==1)return '';if(['SCRIPT','STYLE','IFRAME','IMG','OBJECT'].includes(n.tagName))return '';const text=[...n.childNodes].map(node).join('');if(n.tagName==='BR')return '\n';if(n.classList.contains('formula'))return `<div class="yb-formula">${text}</div>`;return text}return [...template.content.childNodes].map(node).join('')}
 function formatted(text){return StudentMath.render(text)}
 function message(m,i,prefix='msg'){if(m.role==='divider')return `<div class="yb-divider" id="${prefix}-${i}">${esc(m.text)}</div>`;if(m.role==='paper')return `<article class="yb-msg yb-paper" id="${prefix}-${i}"><small>题目${m.text===S.question?' · 24':''}</small><p class="yb-math">${esc(m.text)}</p></article>`;return `<div class="yb-msg yb-${m.role==='user'?'user':'teacher'}" id="${prefix}-${i}">${m.text!==undefined?formatted(m.text):rich(m)}</div>${m.record?`<div class="yb-record-saved">${icon('book')}<span>第 24 题 · 记录</span>${btn('detail','查看','chevron')}</div>`:''}`}
 function renderChat(){newReply=false;const s=S.current();$('#stage').innerHTML=`<div class="yb-chat"><div class="yb-chat-scroll" id="chat-scroll"><div class="yb-messages" id="messages"></div></div><div class="yb-composer-area"><div class="yb-composer-column"><div class="yb-quick" id="quick-actions"></div><form class="yb-composer" id="composer">${s.course?btn('attach','','clip','yb-icon yb-attach','type="button" aria-label="添加作业" title="添加作业"'):''}<textarea id="answer-input" rows="1" placeholder="${s.waitingQuestion?'发下一道题…':'说说你的想法…'}" aria-label="输入回答或题目" maxlength="30000"></textarea><button class="yb-btn yb-icon yb-send" type="submit" aria-label="发送" title="发送">${icon('up')}</button></form></div></div></div>`;renderedSession=s.id;updateChat(false);const input=$('#answer-input');input.value=s.draft||'';resizeInput();input.addEventListener('input',()=>{s.draft=input.value;clearTimeout(draftTimer);draftTimer=setTimeout(()=>S.persist(),300);resizeInput()});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&!matchMedia('(max-width:767px)').matches){e.preventDefault();submit()}});$('#composer').addEventListener('submit',e=>{e.preventDefault();submit()});$('#chat-scroll').addEventListener('scroll',()=>{if(nearBottom())removeNewReply()},{passive:true});requestAnimationFrame(()=>{const scroll=$('#chat-scroll');if(scroll)scroll.scrollTop=positions.get(s.id)??scroll.scrollHeight})}
 function resizeInput(){const input=$('#answer-input');if(!input)return;input.style.height='auto';input.style.height=Math.min(input.scrollHeight,160)+'px';$('.yb-send').disabled=!input.value.trim()||S.pending.has(S.state.current)}
 function nearBottom(){const sc=$('#chat-scroll');return !sc||sc.scrollHeight-sc.scrollTop-sc.clientHeight<=80}
 function updateChat(enter=true){if(view!=='chat'||renderedSession!==S.state.current){if(view==='chat')render();return}const s=S.current(),messages=$('#messages'),scroll=$('#chat-scroll'),follow=nearBottom(),oldCount=Number(messages.dataset.count||0);messages.querySelectorAll('[data-transient]').forEach(e=>e.remove());if(!s.messages.length){scroll.style.display='none';if(!$('.yb-welcome'))scroll.insertAdjacentHTML('afterend',`<div class="yb-welcome">${illustration('paper')}<h1>把题目发来</h1><p>从第一步开始。</p>${btn('sample','试试第 24 题','','yb-secondary')}</div>`)}else{scroll.style.display='';$('.yb-welcome')?.remove();s.messages.slice(oldCount).forEach((m,i)=>{const holder=document.createElement('div');holder.innerHTML=message(m,oldCount+i);while(holder.firstChild){const el=holder.firstChild;messages.append(el);if(enter)animate(el,[{opacity:0,transform:'translateY(8px)'},{opacity:1,transform:'translateY(0)'}],180)}})}messages.dataset.count=String(s.messages.length);if(S.pending.has(s.id))messages.insertAdjacentHTML('beforeend','<div class="yb-typing" data-transient role="status" aria-label="正在回复"><i></i><i></i><i></i></div>');if(s.failure)messages.insertAdjacentHTML('beforeend',`<div class="yb-fail" data-transient role="alert"><span>${esc(s.failure)}</span>${btn('retry','重试','retry')}</div>`);$('#answer-input').placeholder=s.waitingQuestion?'发下一道题…':'说说你的想法…';$('#quick-actions').innerHTML=s.messages.length&&!s.waitingQuestion?btn('help','没懂这一步','help','yb-chip','type="button"')+btn('full-answer','看完整答案','eye','yb-chip','type="button"')+(S.canNext()?btn('next','下一题','plus','yb-chip','type="button"'):''):' ';$('#quick-actions').querySelectorAll('button').forEach(b=>b.disabled=S.pending.has(s.id));resizeInput();if(enter&&s.messages.length>oldCount){if(follow)requestAnimationFrame(()=>scroll.scrollTo({top:scroll.scrollHeight,behavior:reduce()?'instant':'smooth'}));else if(!newReply){newReply=true;scroll.insertAdjacentHTML('afterend',btn('new-reply','新消息','down','yb-new-reply'));$('.yb-new-reply').style.bottom=($('.yb-composer-area').offsetHeight+16)+'px';}}renderSidebar();renderHeader()}
 function removeNewReply(){newReply=false;$('.yb-new-reply')?.remove()}
 function submit(){const input=$('#answer-input'),text=input?.value.trim();if(!text||S.pending.has(S.state.current))return;flushDraft();input.value='';S.send(text);resizeInput()}
 function recordsPage(){return `<div class="yb-page-heading"><h1>题目记录</h1>${btn('review','复习','repeat','yb-secondary')}</div><div class="yb-tools"><label class="yb-search">${icon('search')}<input id="record-search" placeholder="搜索题目、知识点" aria-label="搜索题目或知识点" value="${esc(query)}"></label>${btn('filter','','filter',`yb-icon ${askedOnly?'yb-filter-on':''}`,'aria-label="筛选题目" title="筛选题目"')}</div><div id="record-results" class="yb-list"></div>`}
 function observedQuestions(s){const legacy=(s?.stuck||[]).map(x=>({text:x.text,label:['理解独立性','整理等式','合并两种情况','全概率公式','判断独立性'][x.stage]||'解题时'}));for(const m of s?.messages||[])if(m.role==='user'&&/不会|不懂|为什么|怎么|不知道|相等.*独立|所以.*独立/.test(m.text||'')&&!legacy.some(q=>q.text===m.text))legacy.push({text:m.text,label:'你当时问'});return legacy}
 function renderResults(){const s=S.record(),questions=observedQuestions(s),source='24 条件概率 全概率公式 独立性 '+S.question+' '+questions.map(q=>q.text).join(' ');$('#record-results').innerHTML=s&&(!query||source.toLowerCase().includes(query.toLowerCase()))&&(!askedOnly||questions.length)?`<button class="yb-card yb-record-row" data-action="detail"><span class="yb-record-number">24</span><div class="yb-record-body"><h2>从条件概率证明独立</h2><p>P(A | B) + P(A̅ | B̅) = 1</p><div class="yb-record-meta"><span class="yb-tag">演示记录</span><span class="yb-tag">条件概率</span><span class="yb-tag">独立性</span>${questions.length?`<small>${questions.length} 次追问</small>`:''}</div></div>${icon('chevron','yb-chevron')}</button>`:`<div class="yb-empty">${illustration('book')}<p>${query||askedOnly?'没有匹配的题目':'还没有题目记录'}</p>${!query&&!askedOnly?btn('sample','试试第 24 题','','yb-secondary'):''}</div>`;$('#record-search').oninput=e=>{query=e.target.value;renderResults()}}
 function fold(label,body,ico='book'){return `<details class="yb-fold"><summary>${icon(ico)}${label}${icon('chevron')}</summary><div class="yb-fold-body">${body}</div></details>`}
 function detailPage(){const s=S.record();if(!s)return recordsPage();const quotes=observedQuestions(s);const journey=['从独立性要证明的等式开始。'];if(s.stage>=2||s.messages.some(m=>m.role==='user'&&/P\(A.*=.*P\(A/.test(m.text||'')))journey.push('尝试把题目条件整理为两个概率相等。');if(s.messages.some(m=>m.role==='user'&&/0[.．]3/.test(m.text||'')))journey.push('回答：不区分 B 是否发生，概率还是 0.3。');if(s.messages.some(m=>m.role==='user'&&/理解了|明白了/.test(m.text||'')))journey.push('对讲解作出“理解了”或“明白了”的反馈。');if(s.reasonGiven)journey.push('在判断题中说明了 B 对 A 的概率产生影响。');return `${btn('records','记录','back','yb-back')}<h1 class="yb-detail-title">从条件概率证明独立</h1><div class="yb-detail-meta"><small>第 24 题</small><span class="yb-tag">演示记录</span></div><div class="yb-paper"><p class="yb-math">${esc(S.question)}</p></div>${fold('完整答案',`<p class="yb-math" style="white-space:pre-wrap">${esc(answer)}</p>`,'eye')}<section class="yb-section"><h2>解题步骤</h2><ol class="yb-step-list"><li>用互补关系替换第二项。</li><li>整理出两个条件概率相等，记作 q。</li><li>用全概率公式算出 P(A) = q。</li><li>由 P(A | B) = P(A)，得到独立。</li></ol><div class="yb-concepts">${['条件概率','全概率公式','独立性'].map(t=>`<span class="yb-tag">${t}</span>`).join('')}</div></section><section class="yb-section"><h2>这次怎么学的</h2><div class="yb-journey">${journey.map(p=>`<p>${p}</p>`).join('')}</div></section><section class="yb-section"><h2>当时哪里没懂</h2>${quotes.length?quotes.map(q=>`<div class="yb-quote"><span>${esc(q.label)}</span><p>“${esc(q.text)}”</p></div>`).join(''):'<p>还没有追问记录。</p>'}</section>${s.stage>=4?fold('追加练习','<p>P(A | B) = 0.4，P(A | B̅) = 0.6。A 与 B 独立吗？</p>'+fold('答案','<p>不独立。B 是否发生会改变 A 的概率。</p>','eye')):''}${fold('完整聊天',`<div class="yb-history">${s.messages.map((m,i)=>message({...m,record:false},i,'history')).join('')}</div>`)}<div class="yb-review-actions">${btn('continue-record','继续这道题','back','yb-primary')}${btn('review','加入复习','repeat','yb-secondary')}</div>`}
 function reviewPage(){const s=S.record();return `${btn('records','记录','back','yb-back')}<div class="yb-page-heading"><h1>复习</h1>${s?'<small>1 / 1</small>':''}</div>${s?`<div class="yb-card"><div class="yb-record-meta"><span class="yb-tag">第 24 题</span><small>先自己想</small></div><p class="yb-review-question yb-math" style="margin-top:16px">${esc(S.question)}</p><div id="review-answer" hidden><p class="yb-math" style="white-space:pre-wrap">${esc(answer)}</p><div class="yb-review-actions">${btn('review-know','我会了','check','yb-primary')}${btn('review-again','还不熟','repeat','yb-secondary')}${btn('review-skip','跳过','','yb-ghost')}</div></div><div id="review-start">${btn('review-answer','看答案','eye','yb-primary')}</div></div>`:`<div class="yb-empty">${illustration('book')}<p>还没有可复习的记录</p>${btn('chat','回去做题','','yb-secondary')}</div>`}`}
 function reviewComplete(){const page=$('.yb-page');if(page)page.innerHTML=`${btn('records','记录','back','yb-back')}<div class="yb-empty">${illustration('book')}<h1>这次复习完成了</h1><p>1 道题 · 你标记为“我会了”</p>${btn('review-reset','再复习一次','repeat','yb-secondary')}</div>`}
 function filesPage(){const list=S.state.resources.map((f,i)=>({...f,i})).filter(f=>f.course===S.state.course);return `<div class="yb-page-heading"><h1>课程资料</h1>${btn('add-files','添加文件','plus','yb-primary')}</div><p class="yb-inline-note">仅记录文件名，AI 不会读取文件内容。</p><div class="yb-list">${list.length?list.map(f=>`<div class="yb-card yb-file">${icon('file')}<div><strong>${esc(f.name)}</strong><small>文件名</small></div>${btn('file-menu','','more','yb-icon',`aria-label="管理 ${esc(f.name)}" data-file="${f.i}"`)}</div>`).join(''):`<div class="yb-empty">${illustration('file')}<p>还没有课程资料</p></div>`}</div>`}
 function toast(text){const el=$('#toast');clearTimeout(toastTimer);el.textContent=text;el.hidden=false;animate(el,[{opacity:0,translate:'0 16px'},{opacity:1,translate:'0 0'}],200);toastTimer=setTimeout(async()=>{await animate(el,[{opacity:1},{opacity:0}],160,true);el.hidden=true},2400)}
 function closePopover(){const root=$('#popover-root');if(!root.firstChild)return;const el=root.firstChild,anchor=menuAnchor;menuAnchor=null;el.style.pointerEvents='none';animate(el,[{opacity:1},{opacity:0}],120,true).then(()=>el.remove());anchor?.setAttribute('aria-expanded','false');if(el.contains(document.activeElement)&&anchor?.isConnected)anchor.focus({preventScroll:true})}
 function popover(anchor,html,width=240){if(menuAnchor===anchor){closePopover();return}$('#popover-root').replaceChildren();menuAnchor=anchor;anchor.setAttribute('aria-expanded','true');const el=document.createElement('div');el.className='yb-popover';el.innerHTML=html;el.style.width=width+'px';$('#popover-root').append(el);const r=anchor.getBoundingClientRect(),w=el.offsetWidth,h=el.offsetHeight;const left=Math.max(12,Math.min(innerWidth-w-12,r.left)),top=r.bottom+h+8<innerHeight?r.bottom+6:Math.max(12,r.top-h-6);el.style.left=left+'px';el.style.top=top+'px';animate(el,[{opacity:0,transform:'translateY(4px)'},{opacity:1,transform:'translateY(0)'}],180);const focus=el.querySelector('button,input');focus?.focus({preventScroll:true})}
 function closeNav(){const aside=$('#sidebar');if(!aside.classList.contains('open'))return;aside.classList.remove('open');$('.yb-main').inert=false;$('#mobile-menu').setAttribute('aria-expanded','false');if(reduce()){$('#nav-scrim').hidden=true;aside.style.visibility='';return}aside.style.visibility='visible';animate(aside,[{transform:getComputedStyle(aside).transform},{transform:'translateX(-100%)'}],200,true).then(()=>aside.style.visibility='');animate($('#nav-scrim'),[{opacity:1},{opacity:0}],200,true).then(()=>$('#nav-scrim').hidden=true);navFocus?.focus({preventScroll:true})}
 function openNav(){const aside=$('#sidebar');navFocus=document.activeElement;aside.classList.add('open');$('.yb-main').inert=true;$('#nav-scrim').hidden=false;$('#mobile-menu').setAttribute('aria-expanded','true');animate(aside,[{transform:'translateX(-100%)'},{transform:'translateX(0)'}],260);animate($('#nav-scrim'),[{opacity:0},{opacity:1}],260);$('#new-chat').focus()}
 async function closeDialog(){if(dialogClosing)return;dialogClosing=true;await animate($('#dialog'),[{opacity:1,transform:'scale(1)'},{opacity:0,transform:'scale(.98)'}],150,true);$('#dialog').close();dialogClosing=false}
 function dialog(title,body){closePopover();const d=$('#dialog');d.innerHTML=`<div class="yb-dialog-head"><h2 id="dialog-title">${title}</h2>${btn('close-dialog','','close','yb-icon','type="button" aria-label="关闭"')}</div>${body}`;d.showModal();animate(d,[{opacity:0,transform:'translateY(8px) scale(.97)'},{opacity:1,transform:'translateY(0) scale(1)'}],220)}
 function newCourse(){let color=colors[S.state.courses.length%6];dialog('新建课程',`<form id="course-form"><label for="course-name">课程名称</label><input class="yb-textfield" id="course-name" placeholder="例如：大学物理" maxlength="20" required autofocus><div class="yb-colors" aria-label="课程颜色">${colors.map(c=>`<button type="button" style="--swatch:${c}" aria-label="${c}" data-color="${c}" aria-pressed="${c===color}"></button>`).join('')}</div><div class="yb-dialog-actions">${btn('close-dialog','取消','','yb-ghost','type="button"')}<button class="yb-btn yb-primary" id="create-course" type="submit" disabled>创建</button></div></form>`);$('#course-name').oninput=e=>$('#create-course').disabled=!e.target.value.trim();$('#course-form').onclick=e=>{const b=e.target.closest('[data-color]');if(b){color=b.dataset.color;$('#course-form').querySelectorAll('[data-color]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.color===color)))}};$('#course-form').onsubmit=async e=>{e.preventDefault();const name=$('#course-name').value.trim();if(!name)return;S.addCourse(name);S.state.courseColors||={};S.state.courseColors[name]=color;S.persist();await closeDialog();S.create(name)};$('#course-name').focus()}
 function upload(context){closePopover();uploadContext=context;const input=$('#file-input');input.accept=context==='import'?'.json':'image/*,.pdf,.ppt,.pptx,.doc,.docx,.txt';input.multiple=context!=='import';input.value='';input.click()}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b){if(menuAnchor&&!e.target.closest('.yb-popover'))closePopover();return}const a=b.dataset.action;switch(a){
 case 'new':S.create(S.state.course);break;
 case 'course':{const c=b.dataset.course;if(expanded===c&&S.state.course===c){expanded=null;renderSidebar()}else{expanded=c;S.state.course=c;const s=S.state.sessions.find(s=>(s.course||'')===c);if(s)S.select(s.id);else S.create(c)}break}
 case 'session':S.select(Number(b.dataset.session));break;
 case 'session-menu':popover(b,`<button class="yb-navrow yb-danger" data-action="delete-session" data-session="${b.dataset.session}">${icon('close')}删除会话</button>`);break;
 case 'delete-session':{const id=Number(b.dataset.session),item=S.state.sessions.find(s=>s.id===id);if(!item)break;dialog('删除会话',`<p>删除“${esc(item.title)}”？</p><div class="yb-dialog-actions">${btn('close-dialog','取消','','yb-ghost')}<button class="yb-btn yb-delete" id="confirm-delete">删除</button></div>`);$('#confirm-delete').onclick=async()=>{await closeDialog();S.deleteSession(id);toast('会话已删除')};break;}
 case 'tab':if(b.dataset.view==='chat'&&S.current().course!==S.state.course){const s=S.state.sessions.find(s=>s.course===S.state.course);if(s)S.select(s.id);else S.create()}else route(b.dataset.view);break;
 case 'chat':route();break;case 'records':route('records');break;case 'detail':route('records/24');break;case 'review':route('review');break;case 'add-course':newCourse();break;
 case 'menu':$('#sidebar').classList.contains('open')?closeNav():openNav();break;
 case 'sample':S.sample();break;case 'retry':S.retry();break;
 case 'help':S.send('这一步没懂，请只示范当前这一步。');break;
 case 'full-answer':S.current().answerViewed=true;S.send('请给这道题的简洁完整答案。');break;
 case 'next':S.nextQuestion();$('#answer-input').focus();break;
 case 'new-reply':$('#chat-scroll').scrollTo({top:$('#chat-scroll').scrollHeight,behavior:reduce()?'instant':'smooth'});removeNewReply();break;
 case 'attach':upload('chat');break;case 'add-files':upload('files');break;
 case 'account':popover(b,`<div class="yb-popover-label">本地模式</div><div class="yb-status-row">${icon('disk')}<span>数据仅存本设备</span></div><div class="yb-status-row">${icon('cloud')}<span>云同步未接入</span></div><button class="yb-navrow" data-action="export">${icon('download')}导出记录</button><button class="yb-navrow" data-action="import">${icon('upload')}导入记录</button>`,280);break;
 case 'export':{const url=URL.createObjectURL(new Blob([JSON.stringify(S.state,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='一步-学习记录.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);closePopover();toast('记录已导出');break}
 case 'import':upload('import');break;
 case 'filter':popover(b,`<button class="yb-navrow" data-action="filter-all">${!askedOnly?icon('check'):''}全部</button><button class="yb-navrow" data-action="filter-asked">${askedOnly?icon('check'):''}有追问的题目</button>`);break;
 case 'filter-all':case 'filter-asked':askedOnly=a==='filter-asked';closePopover();render('records');break;
 case 'continue-record':{const s=S.record();if(s){S.select(s.id);requestAnimationFrame(()=>{const m=$('#msg-'+s.messages.findIndex(m=>m.role==='paper'));m?.scrollIntoView({block:'start',behavior:reduce()?'instant':'smooth'})})}break}
 case 'review-answer':$('#review-start').hidden=true;$('#review-answer').hidden=false;animate($('#review-answer'),[{opacity:0,transform:'translateY(8px)'},{opacity:1,transform:'translateY(0)'}],240);break;
 case 'review-know':S.review(S.record(),'know');reviewComplete();break;
 case 'review-again':S.review(S.record(),'again');toast('已留在复习中');route('records/24');break;
 case 'review-skip':route('records');break;
 case 'review-reset':S.review(S.record(),null);render('review');break;
 case 'sessions':popover(b,S.state.sessions.filter(s=>(s.course||'')===b.dataset.course).map(s=>`<button class="yb-navrow" data-action="session" data-session="${s.id}"><span class="yb-nav-name">${esc(s.title)}</span></button>`).join(''),280);break;
 case 'jump':popover(b,S.current().messages.map((m,i)=>['paper','divider'].includes(m.role)?`<button class="yb-navrow" data-action="jump-to" data-index="${i}"><span class="yb-nav-name">${m.role==='paper'?(m.text===S.question?'第 24 题':esc(m.text.slice(0,18))):esc(m.text)}</span></button>`:'').join(''));break;
 case 'jump-to':$('#msg-'+b.dataset.index)?.scrollIntoView({block:'start',behavior:reduce()?'instant':'smooth'});closePopover();break;
 case 'file-menu':popover(b,`<button class="yb-navrow" data-action="rename-file" data-file="${b.dataset.file}">${icon('pen')}重命名</button><button class="yb-navrow" data-action="remove-file" data-file="${b.dataset.file}">${icon('close')}移除</button>`);break;
 case 'remove-file':S.state.resources.splice(Number(b.dataset.file),1);S.persist('resources');closePopover();break;
 case 'rename-file':{const i=Number(b.dataset.file);dialog('文件名称',`<form id="rename-form"><input class="yb-textfield" id="file-name" aria-label="文件名称" value="${esc(S.state.resources[i].name)}" maxlength="200" required><div class="yb-dialog-actions"><button class="yb-btn yb-primary">保存</button></div></form>`);$('#rename-form').onsubmit=async e=>{e.preventDefault();const name=$('#file-name').value.trim();if(name){S.state.resources[i].name=name;S.persist('resources');await closeDialog()}};break}
 case 'close-dialog':closeDialog();break;
 }});
 $('#file-input').onchange=async e=>{const files=[...e.target.files];if(!files.length)return;if(uploadContext==='import'){if(S.pending.size){toast('请等待回复完成后导入');return}try{if(files[0].size>5e6)throw Error();const data=JSON.parse(await files[0].text());dialog('导入记录',`<p>导入会替换本设备的现有记录。</p><div class="yb-dialog-actions">${btn('close-dialog','取消','','yb-ghost')}<button class="yb-btn yb-primary" id="confirm-import">导入</button></div>`);$('#confirm-import').onclick=async()=>{try{S.importState(data);await closeDialog();route();toast('记录已导入')}catch{toast('文件格式不正确')}}}catch{toast('无法导入这个文件')}return}if(uploadContext==='files')S.resources(files);else S.attach(files);toast('仅保存文件名，文件内容未读取')};
 $('#dialog').addEventListener('cancel',e=>{e.preventDefault();closeDialog()});$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog()}});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){closePopover();closeNav()}if(e.key==='Tab'&&$('#sidebar').classList.contains('open')&&matchMedia('(max-width:767px)').matches){const controls=[...$('#sidebar').querySelectorAll('button,a')].filter(x=>x.offsetHeight);const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
 $('#nav-scrim').onclick=closeNav;
 document.addEventListener('click',e=>{const summary=e.target.closest('summary');if(!summary||reduce())return;e.preventDefault();const details=summary.parentElement,body=details.querySelector(':scope>.yb-fold-body'),isOpening=details.dataset.target!=='open'&&!details.open||details.dataset.target==='closed';const from=details.getBoundingClientRect().height;motion.get(details)?.cancel();details.dataset.target=isOpening?'open':'closed';details.open=true;const to=isOpening?summary.offsetHeight+body.scrollHeight:summary.offsetHeight;const a=details.animate([{height:from+'px'},{height:to+'px'}],{duration:isOpening?240:180,easing:isOpening?'cubic-bezier(.2,0,0,1)':'cubic-bezier(.4,0,1,1)'});motion.set(details,a);a.finished.then(()=>{details.open=isOpening;delete details.dataset.target}).catch(()=>{})});
 let touchX=0,touchTime=0;$('#sidebar').addEventListener('pointerdown',e=>{if(e.pointerType!=='touch')return;touchX=e.clientX;touchTime=performance.now()});$('#sidebar').addEventListener('pointerup',e=>{if(e.pointerType==='touch'&&touchX-e.clientX>60&&(touchX-e.clientX)/(performance.now()-touchTime)>.5)closeNav()});
 window.addEventListener('student:change',e=>{if(e.detail==='storage-error'){toast('暂时无法保存，请检查浏览器空间');return}if(e.detail==='navigate'){expanded=S.state.course;route();return}if(e.detail==='messages'){updateChat();return}if(e.detail==='resources'&&view==='files')render();else if(e.detail==='import')route();else renderSidebar()});
 addEventListener('hashchange',parseRoute);addEventListener('resize',()=>{tabIndicator();if(innerWidth>=768)closeNav()});addEventListener('pagehide',flushDraft);
 if(window.visualViewport){const adjust=()=>{const mobile=innerWidth<=767,keyboard=mobile&&innerHeight-visualViewport.height>120;document.body.classList.toggle('keyboard-open',keyboard);$('.yb-app').style.height=mobile?visualViewport.height+'px':'';requestAnimationFrame(tabIndicator)};visualViewport.addEventListener('resize',adjust);visualViewport.addEventListener('scroll',adjust)}
 $('#new-chat').innerHTML=icon('pen')+'新对话';$('#account').innerHTML=icon('disk')+'本机保存<i class="yb-save-dot"></i>';$('#mobile-menu').innerHTML=icon('menu');parseRoute();
})();
